Update JenkinsFile

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -58,37 +58,39 @@ pipeline {
     }
 
     stage('Update Deployment File') {
-    environment {
+      environment {
         GIT_REPO_NAME = "Jenkins-Zero-To-Hero"
         GIT_USER_NAME = "suraj-v86"
-    }
-    steps {
+      }
+      steps {
         withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-            sh '''
-                echo "Checking out the latest code..."
-                git checkout main
-                git pull https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} main --rebase
-                
-                echo "Setting Git user info..."
-                git config user.email "suraj.xyz@gmail.com"
-                git config user.name "Suraj Vasudevan"
-                
-                echo "Updating deployment.yml with new image tag..."
-                if grep -q "replaceImageTag" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml; then
-                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                else
-                    echo "replaceImageTag not found, skipping update!"
-                    exit 1
-                fi
-                
-                echo "Verifying if update was successful..."
-                grep "${BUILD_NUMBER}" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml || (echo "Update failed!" && exit 1)
-                
-                echo "Adding and committing changes..."
-                git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                git commit -m "Update deployment image to version ${BUILD_NUMBER}"
-                git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
-            '''
+          sh '''
+            echo "Checking out the latest code..."
+            git checkout main
+            git pull https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} main --rebase
+            
+            echo "Setting Git user info..."
+            git config user.email "suraj.xyz@gmail.com"
+            git config user.name "Suraj Vasudevan"
+            
+            echo "Updating deployment.yml with new image tag..."
+            if grep -q "replaceImageTag" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml; then
+                sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+            else
+                echo "replaceImageTag not found, skipping update!"
+                exit 1
+            fi
+            
+            echo "Verifying if update was successful..."
+            grep "${BUILD_NUMBER}" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml || (echo "Update failed!" && exit 1)
+            
+            echo "Adding and committing changes..."
+            git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+            git commit -m "Update deployment image to version ${BUILD_NUMBER}"
+            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
+          '''
         }
+      }
     }
-}
+  } 
+} 
